import { readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { loadGroupedCoreDataset } from '../../server/coreOperationsGroupedDataset.ts';
import { CORE_ROBUST_PROTOCOL, evaluateCoreRobustness } from '../../server/coreOperationsRobustEvaluation.ts';
import { coreEnsembleAgreement, type FittedTrainingResult } from '../../server/coreOperationsFittedRl.ts';
const directory=process.argv[2];
const validation=JSON.parse(await readFile(`${directory}/robust-validation.json`,'utf8'));
const protocol=JSON.parse(await readFile(`${directory}/protocol.json`,'utf8'));
const results:FittedTrainingResult[]=await Promise.all(protocol.configuration.seeds.map(async(seed:number)=>JSON.parse(await readFile(`${directory}/seed-${seed}.json`,'utf8'))));
if(!validation.gate.passed||!results.every((r)=>r.convergence.passed)) throw new Error('validation or convergence failed; final evaluation remains sealed');
const policies=results.map((r)=>r.policy);
const hash=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
const sourceFiles=Object.fromEntries(await Promise.all(['server/coreOperationsRlEngine.ts','server/coreOperationsFittedRl.ts','server/coreOperationsRobustEvaluation.ts','server/coreOperationsGroupedDataset.ts','server/portBusinessDataset.ts','shared/coreOperationsRlContract.ts'].map(async(f)=>[f,hash(await readFile(f))])));
await writeFile(`${directory}/final-test-lock.json`,JSON.stringify({generatedAt:new Date().toISOString(),protocol:CORE_ROBUST_PROTOCOL,sourceFiles,policySha256:hash(JSON.stringify(policies)),selection:'validation-only, frozen before one final historical regression evaluation',datasetFingerprint:protocol.datasetFingerprint},null,2),{flag:'wx'});
const dataset=await loadGroupedCoreDataset();
if(dataset.fingerprint!==protocol.datasetFingerprint)throw new Error('dataset changed');
const previous=JSON.parse(await readFile('reports/core-operations-rl-champion-v1.json','utf8')).training.champion.seedPolicies;
const evaluation=evaluateCoreRobustness(policies,previous,dataset.testRecords);
const result={evaluation,agreement:coreEnsembleAgreement(policies,dataset.testRecords),previousAgreement:coreEnsembleAgreement(previous,dataset.testRecords)};
await writeFile(`${directory}/final-test.json`,JSON.stringify(result,null,2),{flag:'wx'});
console.log(JSON.stringify({passed:evaluation.gate.passed,checks:evaluation.gate.checks,agreement:result.agreement,previousAgreement:result.previousAgreement},null,2));
