export const RL_OPERATIONAL_CALIBRATION = {
  id: 'public-aggregate-conservative-v2',
  evidenceLevel: 'bounded_scenario_assumption',
  capacityProxy: {
    quantile: 0.9,
    multiplier: 1,
    method: 'train-p90-service-envelope',
  },
  stressTest: {
    arrivalMultiplier: 1.05,
    capacityMultiplier: 0.98,
    label: '5% arrival surge with 2% temporary capacity loss',
  },
  actions: [
    {
      id: 'hold-plan',
      label: '保持计划',
      detail: '按当前到港计划与可用能力执行',
      deferredDemand: 0,
      divertedDemand: 0,
      capacityMultiplier: 1,
      carbonMultiplier: 1,
      safetyModifier: 0,
      targetSpeedKnots: 12,
      arrivalShiftMinutes: 0,
    },
    {
      id: 'eco-speed',
      label: '低碳航速平滑',
      detail: '在不改变航线的前提下小幅平滑到港波动',
      deferredDemand: 0.005,
      divertedDemand: 0,
      capacityMultiplier: 0.997,
      carbonMultiplier: 0.98,
      safetyModifier: -0.002,
      targetSpeedKnots: 11.5,
      arrivalShiftMinutes: 5,
    },
    {
      id: 'arrival-window',
      label: '错峰到港窗口',
      detail: '在授权窗口内小比例后移到港需求',
      deferredDemand: 0.02,
      divertedDemand: 0,
      capacityMultiplier: 1,
      carbonMultiplier: 0.995,
      safetyModifier: -0.002,
      targetSpeedKnots: 11.8,
      arrivalShiftMinutes: 15,
    },
    {
      id: 'port-diversion',
      label: '邻港协同分流',
      detail: '仅对小比例候选船流生成邻港协同建议',
      deferredDemand: 0,
      divertedDemand: 0.01,
      capacityMultiplier: 0.995,
      carbonMultiplier: 1.01,
      safetyModifier: 0.002,
      targetSpeedKnots: 11.8,
      arrivalShiftMinutes: 5,
    },
    {
      id: 'capacity-control',
      label: '泊位能力重配置',
      detail: '通过泊位与服务资源重排提供有限的短时能力增益',
      deferredDemand: 0.005,
      divertedDemand: 0,
      capacityMultiplier: 1.02,
      carbonMultiplier: 1.005,
      safetyModifier: 0.003,
      targetSpeedKnots: 12,
      arrivalShiftMinutes: 5,
    },
  ],
} as const;

export type RlOperationalAction = (typeof RL_OPERATIONAL_CALIBRATION.actions)[number];
